# Generated by Django 4.2.2 on 2023-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('type_body', models.CharField(max_length=25)),
                ('engine', models.FloatField()),
            ],
        ),
    ]
